### ISSUE TITLE
Alt attributes

### ISSUE THREAD

**Issue by aubreywullschleger** [SandraSw/prj-rev-bwfs-dasmoto#3]
Subtlety for errors!  Make sure to use descriptive `alt` attributes on your `<img>` elements like this:  `<img src="Resources/hacksaw.jpeg" alt="hacksaw paint brushes" />` as this is best practice and makes your site more accessible.

Example: https://github.com/SandraSw/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L16

**Comment by SandraSw** [comment]
Hi Aubrey!

Thanks for your review and valuable feedbacks! I'll use alt attribute for my next projects!

Sandra
