### ISSUE TITLE
Concise CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [SandraSw/prj-rev-bwfs-dasmoto#5]
Simplify! Consider using group selectors for any repeated styles in your CSS. For example you could use:
```
.hacksaw h2,
.frames h2,
.finnish h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
Then remove the `font-size`, `font-weight`, and `color` styles from the `.hacksaw h2`, `.frames h2`, and `.finnish h2` selectors. This will help the CSS to be more concise!

**Comment by SandraSw** [comment]
Thanks for that, I completely forgot the "," selector :)
