### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [SandraSw/prj-rev-bwfs-dasmoto#6]
Grade: Meets expectations

Summary:
Great work on this project! I like your organized HTML and your use of `<div>` elements.

A couple things to work on here would be: 1. descriptive `alt` attributes for your `<img>` elements and 2. using group selectors for any repeated styles in your CSS.

Next, I challenge you to research and implement media queries to make your page responsive for all screen widths. This is a challenge I think you are ready for based on your work here! Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by SandraSw** [comment]
Thanks a lot Aubrey for your feedbacks, this will help me going further in my learning!
I'll have a look at the resources you provided, thanks a lot!
